# Standard Sobol analysis
# Note: if you want to run the code for a replication check, all the output results should be the same as
#       the example outputs except for the computational time (because the machines are different). 
#       This note applies to all the scripts in this study.


# Remove all existing environment and plots
rm(list = ls())
graphics.off()

setwd("/storage/group/pches/default/users/svr5482/Sensitivity_paper_revision")

source("0_library.R")

print("1_Sobol5_SR.R") 

T_Sobol<- vector()
T_check_Sobol<- vector()
all_eval_times<- vector()

# Define the test model in each dimension and perform the Sobol analysis
k=5
# d dimensional model
set.seed(k)
d <- D[k]
print(d)

# Folder for d dimension test scenario under the working directory
# "Data" is the folder that saves all the relevant parameters during the tests
folder <- paste0(folderpath,d,"D")

if (!dir.exists(folder)) dir.create(folder)
if (!dir.exists(paste0(folder,"/Sobol_LHS"))) dir.create(paste0(folder,"/Sobol_LHS"))

size_counter<- 0
# For each considered sample size, perform the Sobol analysis
for (m in 1:length(tot_size)){
  
  # "sensobol" package has a special design for a sobol matrix used for the analysis,
  #     N here is the length of the matrix.
  # The relationship between N and the sample size (when calculating up to 2nd order indices) is:
  #     sample size = N*(d+2+d*(d-1)/2)
  # Note we take the nearest integer, hence the actual sample size is an approximation of the list of sample
  #     size we consider. 
  N <- floor(tot_size[m]/(d+2+d*(d-1)/2))
  
  if(size_counter==0) test_cond<- N>=2
  if(size_counter>0) test_cond<- N >= max(2,1+N_last)
  # if N < 2, increase size directly
  if (test_cond){
    size_counter<- size_counter+1
    
    # Sensitivity analysis time
    sens_start.time<-Sys.time()
    
    # Input matrix and output. The input matrix is generated by the Sobol sequence algorithm.
    if(size_counter==1){
      #mat <- sobol_matrices(N = N, params = as.character(c(1:d)), order = "second")
      
      #start.time<- Sys.time()
      mat <- randomLHS(tot_size[m],d)
      #end.time<- Sys.time()
      #LHS_time <- difftime(end.time,start.time, units = "secs")
      #T_sobolLHS_Sobol<- c(T_sobolLHS_Sobol,LHS_time)
    }
    if(size_counter>1){
      #old_mat <- mat
      #N_diff<- N-N_last
      #new_mat <- sobol_matrices(N = N_diff, params = as.character(c(1:d)), order = "second",
      #                          init=FALSE)
      #mat <- rbind(old_mat,new_mat)
      
      #start.time<- Sys.time()
      mat<- augmentLHS(mat,tot_size[m]-tot_size_last)
      #end.time<- Sys.time()
      #LHS_time <- difftime(end.time,start.time, units = "secs")
      #T_sobolLHS_Sobol<- c(T_sobolLHS_Sobol,LHS_time)
    }      
    
    X <- split(t(mat), rep(1:dim(mat)[1], each = d))
    
    Sobol_convergesize<- nrow(mat)
    print(paste0("Sobol_convergesize: ",Sobol_convergesize))
    
    # Model total evaluation time
    start.time<-Sys.time()
    Y <- sapply(X, Testmodel)
    end.time<-Sys.time()
    print("Model run complete")
    # Model evaluation time
    eval_time <- difftime(end.time,start.time,units = "secs")/length(Y)
    all_eval_times<- c(all_eval_times,eval_time)
    
    S <- sobol_indices_boot(Y=Y,N=N,params = as.character(c(1:d)),
                            boot=TRUE,R=100,order="second")
    
    sens_end.time<-Sys.time()
    time_sobol<-difftime(sens_end.time,sens_start.time,units = "secs")
    T_Sobol<-c(T_Sobol,time_sobol)
    print("Sobol complete")
    
    # convergence of ranking:
    start.time <- Sys.time()
    
    Sens <- S$boot$t[ ,c((1+d):(2*d))]
    Rank <- t(apply(Sens, 1, rank))
    for (boot_ind1 in 1:99){
      T <- boot_ind1
      for (boot_ind2 in (T+1):100){
        Rho <- rep(NA,d)
        Weights <- rep(NA,d)
        for (para_ind in 1:d){
          Weights[para_ind] <- (max(Sens[boot_ind1,para_ind],max(Sens[boot_ind2,para_ind])))^2
        }
        Weights_sum <- sum(Weights)
        for (para_ind in 1:d){
          Rho[para_ind] <- abs(Rank[boot_ind1,para_ind]-Rank[boot_ind2,para_ind])*
            Weights[para_ind]/Weights_sum
        }
        if (boot_ind2 == 2){
          Rho_all <- Rho
        } else{
          Rho_all <- append(Rho_all,Rho)
        }
      }
    }
    Rho_all <- matrix(Rho_all, nrow = d)
    Rho_all <- apply(Rho_all, 2, sum)
    
    end.time <- Sys.time()
    time_check <- difftime(end.time,start.time,units = "secs")
    T_check_Sobol<- c(T_check_Sobol,time_check)
    print("Sobol check complete")
    
    tot_size_last<- tot_size[m]
    N_last<- N
    
    save(T_Sobol,file = paste0(folder,"/Sobol_LHS/T_Sobol"))
    save(T_check_Sobol,file=paste0(folder,"/Sobol_LHS/T_check_Sobol"))
    save(S,file=paste0(folder,"/Sobol_LHS/S_Sobol"))
    save(Sobol_convergesize,file=paste0(folder,"/Sobol_LHS/Sobol_convergesize"))
    save(all_eval_times,file = paste0(folder,"/Sobol_LHS/all_eval_times"))
    
    print(paste0("95%: ",quantile(Rho_all,probs = 0.95, na.rm = TRUE)))
    if (!any(is.na(Rho_all))){
      #print(quantile(Rho_all,probs = 0.95, na.rm = TRUE))
      if (quantile(Rho_all,probs = 0.95, na.rm = TRUE) < 1){
        avg_eval_time<- mean(all_eval_times)
        save(avg_eval_time,file = paste0(folder,"/Sobol_LHS/avg_eval_time"))
        break
      }
    }
    
  }
}

